---
abstract: 'Work with ITS-decorated documents'
author:
  - 'Nathan Glenn <garfieldnate@gmail.com>'
build_requires:
  Data::Section::Simple: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Message: 0
  IO::Compress::Gzip: 0
  LWP::UserAgent: 0
  Log::Any::Test: 0
  Module::Build: 0.3601
  Test::Base: 0
  Test::Base::Filter: 0
  Test::Exception: 0
  Test::HTML::Differences: 0
  Test::More: 0.88
  Test::NoWarnings: 0
  Test::Warn: 0
  Test::XML: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300036, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ITS-WICS
no_index:
  directory:
    - 'inc t xt examples share eg mylib'
provides:
  ITS:
    file: lib/ITS.pm
    version: 0.02
  ITS::DOM:
    file: lib/ITS/DOM.pm
    version: 0.02
  ITS::DOM::Element:
    file: lib/ITS/DOM/Element.pm
    version: 0.02
  ITS::DOM::Node:
    file: lib/ITS/DOM/Node.pm
    version: 0.02
  ITS::DOM::Value:
    file: lib/ITS/DOM/Value.pm
    version: 0.02
  ITS::HTMLRuleExtractor:
    file: lib/ITS/HTMLRuleExtractor.pm
    version: 0.02
  ITS::Rule:
    file: lib/ITS/Rule.pm
    version: 0.02
  ITS::RuleContainer:
    file: lib/ITS/RuleContainer.pm
    version: 0.02
  ITS::WICS:
    file: lib/ITS/WICS.pm
    version: 0.02
  ITS::WICS::FutureNode:
    file: lib/ITS/WICS/FutureNode.pm
    version: 0.02
  ITS::WICS::FutureNodeManager:
    file: lib/ITS/WICS/FutureNodeManager.pm
    version: 0.02
  ITS::WICS::GuiLogger:
    file: lib/ITS/WICS/GuiLogger.pm
    version: 0.02
  ITS::WICS::LogUtils:
    file: lib/ITS/WICS/LogUtils.pm
    version: 0.02
  ITS::WICS::Reduce:
    file: lib/ITS/WICS/Reduce.pm
    version: 0.02
  ITS::WICS::XLIFF2HTML:
    file: lib/ITS/WICS/XLIFF2HTML.pm
    version: 0.02
  ITS::WICS::XML2HTML:
    file: lib/ITS/WICS/XML2HTML.pm
    version: 0.02
  ITS::WICS::XML2XLIFF:
    file: lib/ITS/WICS/XML2XLIFF.pm
    version: 0.02
  ITS::WICS::XML2XLIFF::CustomSegmenter:
    file: lib/ITS/WICS/XML2XLIFF/CustomSegmenter.pm
    version: 0.02
  ITS::WICS::XML2XLIFF::ITSProcessor:
    file: lib/ITS/WICS/XML2XLIFF/ITSProcessor.pm
    version: 0.02
  ITS::WICS::XML2XLIFF::ITSSegmenter:
    file: lib/ITS/WICS/XML2XLIFF/ITSSegmenter.pm
    version: 0.02
  ITS::XMLRuleExtractor:
    file: lib/ITS/XMLRuleExtractor.pm
    version: 0.02
requires:
  Carp: 0
  Data::Dumper: 0
  Encode: 0
  Exporter::Easy: 0
  Getopt::Lucid: 0
  HTML::HTML5::Parser: 0
  HTML::HTML5::Writer: 0
  List::MoreUtils: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Log::Any::Adapter::Base: 0
  Log::Any::Adapter::Util: 0
  Path::Tiny: 0
  Try::Tiny: 0
  URI: 0
  Wx: 0
  Wx::Perl::Packager: 0
  XML::LibXML: 0
  autodie: 0
  base: 0
  feature: 0
  parent: 0
  perl: 5.014
  strict: 0
  warnings: 0
version: 0.02
x_BuiltWith:
  modules:
    Carp: 1.26
    Data::Dumper: 2.145
    Data::Section::Simple: 0.03
    Encode: 2.45
    Exporter::Easy: 0.16
    File::Find: 1.20
    File::Path: 2.08_01
    File::Slurp: 9999.19
    File::Temp: 0.2301
    FindBin: 1.51
    Getopt::Lucid: 1.05
    HTML::HTML5::Parser: 0.301
    HTML::HTML5::Writer: 0.201
    HTTP::Message: 6.03
    IO::Compress::Gzip: 2.062
    LWP::UserAgent: 6.04
    List::MoreUtils: 0.33
    Log::Any: 0.15
    Log::Any::Adapter: 0.11
    Log::Any::Adapter::Base: 0.11
    Log::Any::Adapter::Util: 0.11
    Log::Any::Test: 0.15
    Module::Build: 0.4005
    Path::Tiny: 0.043
    Pod::Coverage::TrustPod: 0.100002
    Test::Base: 0.60
    Test::Base::Filter: NA(undef)
    Test::CPAN::Meta: 0.23
    Test::Exception: 0.31
    Test::HTML::Differences: 0.03
    Test::More: 0.98
    Test::NoWarnings: 1.04
    Test::Pod: 1.45
    Test::Pod::Coverage: 1.08
    Test::Warn: 0.24
    Test::XML: 0.08
    Try::Tiny: 0.12
    URI: 1.60
    Wx: 0.9922
    Wx::Perl::Packager: 0.27
    XML::LibXML: 2.0100
    autodie: 2.16
    base: 2.18
    feature: 1.27
    parent: 0.225
    perl: 'NA(skipped: perl)'
    strict: 1.07
    utf8: 1.09
    version: 0.9903
    warnings: 1.13
  perl:
    original: v5.16.1
    qv: 1
    version:
      - 5
      - 16
      - 1
  platform: MSWin32
x_Dist_Zilla:
  perl:
    version: 5.016001
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: Phase_Begins
      version: 0.00
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.013
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: GatherDir
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::GenerateFile
      name: MANIFEST.SKIP
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: ReportVersions::Tiny
      version: 1.08
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 2.001
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: Test::Perl::Critic
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: Test::DistManifest
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: Test::Version
      version: 0.002004
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: MetaTests
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: Test::CPAN::Meta::JSON
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: MojibakeTests
      version: 0.5
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: PodCoverageTests
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: Test::Portability
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: Test::Synopsis
      version: 2.000002
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: Test::UnusedVars
      version: 2.000003
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: Test::Pod::LinkCheck
      version: 1.001
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: Test::CPAN::Changes
      version: 0.005
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: Test::Kwalitee
      version: 2.03
    -
      class: Dist::Zilla::Plugin::Prepender
      name: Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: ExecDir
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: ShareDir
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: 0
          show_uname: 0
      name: MetaData::BuiltWith
      version: 0.03000100
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: MakeMaker
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: DualBuilders
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: ReadmeFromPod
      version: 0.18
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeAnyFromPod
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: 0.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: RunExtraTests
      version: 0.007
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: Git::CommitBuild
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 2.013
    -
      class: Dist::Zilla::Plugin::ReportPhase
      name: Phase_Ends
      version: 0.00
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300036
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300036
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300036
