=head1 WICS Converter User Guide

This guide explains how to use the WICS converters, WICS and WICS-GUI.

=head2 Overview

=head3 ITS

ITS, or the Internationalization Tag Set, is a standard for adding internalization-related information to XML, XLIFF, and HTML5 documents. For example, using this tag set you can mark parts of a document as untranslatable, as needing special treatment for a given locale, or as being related to a given media resource.

ITS provides for two methods of annotating documents. The first is through local attributes. The second is through global rules, which use a query language (XPath for now) to select nodes to be annotated.

In XML, ITS information is added to the document via markup in the C<http://www.w3.org/2005/11/its> namespace.

In HTML5, most ITS attributes begin with C<its->, but the ITS standard also strives to re-use attributes already available in HTML5, such as C<translate>. Elements in the ITS namespace can be used, if contained in a C<< <script type="application/its+xml" >> element. ITS-decorated HTML5 files can be validated with an online tool L<here|http://validator.w3.org/nu/>.

XLIFF documents can use XML ITS, but can additionally use markup from the C<http://www.w3.org/ns/its-xliff/> namespace, which was created to allow all ITS information to be localizable.

=head3 WICS

WICS stands for "Work In Context System". It is a project which seeks to make ITS markup more useful by displaying it in a more user-friendly manner within a web browser. It has two components:

* A converter for generating HTML5 or XLIFF from original documents (this project)
* JavaScript to display ITS data in Web browsers

The applications described in this document accomplish four file conversion tasks:

1. Convert ITS-decorated XML into HTML5 for displaying the contents and ITS metadata (XML2HTML)
2. Reduce ITS-decorated HTML5 documents to be usable as a single file (HTML reducer)
3. Convert ITS-decorated XLIFF into HTML5 for displaying the contents of C<< <source> >> and and C<< <target> >> elements with associated ITS metadata (XLIFF2HTML)
4. Extract text segments and their associated ITS metadata and create an XLIFF file with equivalent ITS decorating the translation units (XML2XLIFF). This application is of limited functionality and is demonstrated through only one sample conversion.

Both the WICS and WICS-GUI application can accomplish all four tasks, but WICS requires the use of a command line.

=head2 Using the converters

=head3 Included sample files

C<TODO:> What sample files?

There are three types of files in the samples: XML, HTML5, and XLIFF. The XML files end in C<.xml>, the HTML5 in C<.html> and the XLIFF in C<.xlf>. The XML files can be used as input to the XML2XLIFF and XML2HTML converters, the HTML files can be used as input to the HTML reducer, and the XLIFF files (including the ones generated by XML2XLIFF) can be used as input to the XLIFF2HTML converter.

=head3 WICS-GUI

When you open WICS-GUI, you should see a small window similar to the one shown below. It may take a few moments to start, so please be patient. It takes longer the first time you use it.

=begin html

<center>
    <img
        src="WICS-GUI.png"
        alt="WICS-GUI snapshot"
        title="WICS-GUI snapshot"
        style="text-align:center;" />
</center>

=end html

Upon double-clicking on the task that you wish to perform, you are given another window like that shown below:

=begin html

<center>
    <img
        src="WICS-GUI-choose-file.png"
        alt="WICS-GUI snapshot"
        title="WICS-GUI snapshot" />
</center>

=end html

Click on C<Choose file...> to choose one or more files that you would like to process with the chosen task. If you have chosen C<XML2HTML>, for example, then you should choose one more more ITS-decorated XML files that you would like to convert to HTML for viewing in your web browser.

After you have chosen the files you would like to process, they are listed in the white box. Upon clicking C<Convert> to process the listed files, another window containing the application logs appears:

=begin html

<center>
    <img
        src="WICS-GUI-logs.png"
        alt="WICS-GUI snapshot"
        title="WICS-GUI snapshot" />
</center>

=end html

The application logs information about what it is doing while processing each input file. You'll know that a file conversion was sucessful if you see a blue message saying that an output file was written.

If you see a red message instead, then something went wrong. You should refer to the printed message for more details, but in general there are two possible problems:

=over

=item 1

The input file you provided is not well-formed. For example, your XML file might have a mismatched tag (like C<< <xml><a></b></xml> >>), or your might have two separate elements with the same C<xml:id> attribute value.

=item 2

The input file you provided should not be processed by the given converter. For example, you might provide a file containing only an C<< <its:rules> >> element. This kind of file is meant to be referenced from another file with ITS metadata, and should not be processed directly. You should instead process the file that references it.

=back

The C<copy> button at the top of the window copies all of the log contents from the window onto your clipboard so that you can paste it into another application such as a text editor or email client.

=head3 WICS

This application runs from the command line. The usage is C<< WICS [-w] --[task] -i <file> >>. The options are described below:

=over

=item C<--xml2html>, C<--xliff2html>, C<--xml2xliff> or C<--reduceHtml>

This argument is required. It pecifies which operation is to be carried out on the input file. Each name corresponds to a WICS conversion task.

=item C<-i file> or C<-input file>

This argument is required. It provides the path to the input file to convert. This option may be provided multiple times to convert multiple files.

=item C<-w> or C<--overwrite>

This option Specifies that the script may overwrite existing files when printing the conversion results. Filenames are created by stripping the extension from the input file and replacing it with the extension for the target format (html, xliff, etc.). If overwriting existing files is not permitted, additional numbers (-1, -2, etc.) will be appended to the filename to insure uniqueness.

This script will never write over the input file.

=back

